# Generated by Django 6.0.3 on 2026-04-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_icecream'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icecream',
            name='in_stock',
        ),
        migrations.AddField(
            model_name='icecream',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
