# Generated by Django 6.0.3 on 2026-05-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_icecream_in_stock_icecream_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
